name: Go Build

# 触发条件：当有代码推送到 main 分支或发起 pull request 时触发
on:
  push:
    tags:
      - 'v*.*.*'

# 定义任务
jobs:
  build:
    # 运行环境：最新版本的 Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # 指定 Go 版本

      # 3. 下载依赖
      # - name: Download dependencies
        # run: go mod download
      - name: Extract tag name
        id: tag_name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # 5. 构建项目
      - name: Build
        run: bash build.sh ${{ env.TAG }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "release/**"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Update Homebrew Formula
        run: |
          # 克隆 Homebrew Tap 仓库
          git clone https://github.com/helson-lin/homebrew-tap.git
          cd homebrew-tap

          SHA256_ARM=$(shasum -a 256 ../release/doke-${GITHUB_REF#refs/tags/}-darwin-arm64.tar.gz | awk '{print $1}')
          SHA256_INTEL=$(shasum -a 256 ../release/doke-${GITHUB_REF#refs/tags/}-darwin-amd64.tar.gz | awk '{print $1}')

          # 更新 Formula 文件
          sed -i "s|url \".*\"|url \"https://github.com/helson-lin/doke/releases/download/${GITHUB_REF#refs/tags/}/doke-${GITHUB_REF#refs/tags/}-darwin-arm64.tar.gz\"|" doke.rb
          sed -i "s|sha256 \".*\"|sha256 \"$SHA256_ARM\"|" doke.rb  # 更新 ARM 的 SHA256

          # 更新 Intel 的 URL 和 SHA256
          sed -i "s|url \".*amd64.tar.gz\"|url \"https://github.com/helson-lin/doke/releases/download/${GITHUB_REF#refs/tags/}/doke-${GITHUB_REF#refs/tags/}-darwin-amd64.tar.gz\"|" doke.rb
          sed -i "s|sha256 \".*\"|sha256 \"$SHA256_INTEL\"|" doke.rb  # 更新 Intel 的 SHA256

          sed -i "s|version \".*\"|version \"${GITHUB_REF#refs/tags/}\"|" doke.rb

          # 提交并推送更改
          git config --global user.name "helsonlin"
          git config --global user.email "helsonlin@163.com"
          git add doke.rb
          git commit -m "Update doke to ${GITHUB_REF#refs/tags/}"
          git push https://${{ secrets.TOKEN }}@github.com/helson-lin/homebrew-tap.git main
